services:
  backend:
    build:
      dockerfile: backend/Dockerfile
      context: .
    ports:
      - "8080:8080"
    volumes:
      - "./data:/app/data"
    env_file:
      - ./.env
  postgres:
    image: postgres:17.2
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: miku_push
      POSTGRES_PASSWORD: miku_push
      POSTGRES_DB: miku_push

volumes:
  postgres: